/**
 * PDF Export Service
 *
 * Generates a professional A4 participant report PDF for a given event
 * using pdfkit.  The service returns a readable stream that the controller
 * can pipe directly into the HTTP response.
 *
 * Layout:
 *   1. Header — Eventopia branding + "Participant Report"
 *   2. Event metadata block
 *   3. Participant table (S.No, Name, Email, College, Inst. Type, Registered)
 *   4. Footer on every page — "Generated by Eventopia · Page N"
 */

const PDFDocument = require('pdfkit');

// ── Colour palette (matches Eventopia indigo brand) ──────────────────
const COLORS = {
  brand:      '#4f46e5',
  brandLight: '#eef2ff',
  dark:       '#1e293b',
  medium:     '#475569',
  light:      '#94a3b8',
  white:      '#ffffff',
  border:     '#e2e8f0',
  rowAlt:     '#f8fafc',
};

// ── Helpers ──────────────────────────────────────────────────────────
const formatDate = (d) => {
  if (!d) return 'N/A';
  return new Date(d).toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
};

const formatDateTime = (d) => {
  if (!d) return 'N/A';
  return new Date(d).toLocaleString('en-IN', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
};

const truncate = (str, max) => {
  if (!str) return '';
  return str.length > max ? str.substring(0, max - 1) + '…' : str;
};

// ── Main export function ─────────────────────────────────────────────

/**
 * @param {Object} event      – Mongoose event document (plain or lean)
 * @param {Array}  participants – Array of populated User documents
 * @returns {PDFDocument}      – A readable stream (pipe to res)
 */
function generateParticipantPDF(event, participants) {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 60, left: 50, right: 50 },
    info: {
      Title: `Participant Report - ${event.title}`,
      Author: 'Eventopia',
      Subject: 'Event Participant Export',
    },
    bufferPages: true, // enables footer on every page
  });

  const pageWidth  = doc.page.width;
  const contentWidth = pageWidth - 100; // 50 left + 50 right

  // ── 1. Header ────────────────────────────────────────────────────
  doc.rect(0, 0, pageWidth, 100).fill(COLORS.brand);

  doc.fontSize(24).fillColor(COLORS.white).font('Helvetica-Bold')
    .text('Eventopia', 50, 30, { width: contentWidth });

  doc.fontSize(11).fillColor('#c7d2fe').font('Helvetica')
    .text('Participant Report', 50, 60, { width: contentWidth });

  doc.moveDown(2);
  let y = 120;

  // ── 2. Event metadata block ──────────────────────────────────────
  const meta = [
    ['Event Name',           event.title],
    ['Organizer',            event.organizer],
    ['College',              event.college],
    ['Institution Type',     event.institutionType],
    ['Event Type',           event.type],
    ['Venue',                event.venue],
    ['Event Date',           formatDate(event.date)],
    ['Registration Deadline', formatDate(event.registrationDeadline)],
    ['Total Participants',   String(participants.length)],
    ['Report Generated On',  formatDateTime(new Date())],
  ];

  // Background box
  const metaHeight = meta.length * 22 + 20;
  doc.roundedRect(50, y, contentWidth, metaHeight, 4)
    .fill(COLORS.brandLight);

  y += 12;
  meta.forEach(([label, value]) => {
    doc.fontSize(9).fillColor(COLORS.medium).font('Helvetica-Bold')
      .text(label + ':', 65, y, { width: 160, continued: false });
    doc.fontSize(9).fillColor(COLORS.dark).font('Helvetica')
      .text(value || 'N/A', 230, y, { width: contentWidth - 195 });
    y += 22;
  });

  y += 20;

  // ── 3. Participant table ─────────────────────────────────────────
  const columns = [
    { header: '#',               width: 35,  align: 'center' },
    { header: 'Name',            width: 120, align: 'left'   },
    { header: 'Email',           width: 145, align: 'left'   },
    { header: 'College',         width: 110, align: 'left'   },
    { header: 'Inst. Type',      width: 55,  align: 'center' },
    { header: 'Registered On',   width: 90,  align: 'center' },
  ];

  const tableX = 50;
  const rowHeight = 22;

  // Draw table header
  const drawTableHeader = (startY) => {
    doc.rect(tableX, startY, contentWidth, rowHeight + 4).fill(COLORS.brand);
    let xPos = tableX + 6;
    columns.forEach((col) => {
      doc.fontSize(8).fillColor(COLORS.white).font('Helvetica-Bold')
        .text(col.header, xPos, startY + 7, {
          width: col.width - 8,
          align: col.align,
        });
      xPos += col.width;
    });
    return startY + rowHeight + 4;
  };

  y = drawTableHeader(y);

  // Draw rows
  participants.forEach((participant, index) => {
    // Check if we need a new page
    if (y + rowHeight > doc.page.height - 70) {
      doc.addPage();
      y = 50;
      y = drawTableHeader(y);
    }

    const isAlt = index % 2 === 1;
    if (isAlt) {
      doc.rect(tableX, y, contentWidth, rowHeight).fill(COLORS.rowAlt);
    }

    // Bottom border
    doc.moveTo(tableX, y + rowHeight)
      .lineTo(tableX + contentWidth, y + rowHeight)
      .strokeColor(COLORS.border).lineWidth(0.5).stroke();

    const rowData = [
      String(index + 1),
      truncate(participant.name || 'N/A', 22),
      truncate(participant.email || 'N/A', 28),
      truncate(participant.college || 'N/A', 20),
      participant.institutionType || 'N/A',
      formatDate(participant.createdAt),
    ];

    let xPos = tableX + 6;
    rowData.forEach((value, colIdx) => {
      const col = columns[colIdx];
      doc.fontSize(8).fillColor(COLORS.dark).font('Helvetica')
        .text(value, xPos, y + 6, {
          width: col.width - 8,
          align: col.align,
        });
      xPos += col.width;
    });

    y += rowHeight;
  });

  // Empty table message
  if (participants.length === 0) {
    y += 10;
    doc.fontSize(10).fillColor(COLORS.light).font('Helvetica-Oblique')
      .text('No participants have registered for this event yet.', tableX, y, {
        width: contentWidth, align: 'center',
      });
  }

  // ── 4. Footer on every page ──────────────────────────────────────
  const totalPages = doc.bufferedPageRange().count;
  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);
    const footerY = doc.page.height - 40;

    doc.fontSize(7).fillColor(COLORS.light).font('Helvetica')
      .text(
        `Generated by Eventopia  •  Page ${i + 1} of ${totalPages}`,
        50, footerY,
        { width: contentWidth, align: 'center' }
      );
  }

  doc.end();
  return doc;
}

module.exports = { generateParticipantPDF };
